spring:
    profiles:
        active: local

logging:
  level:
    no.skatteetaten.aurora.gorg: INFO
    org:
      hibernate: WARN
      springframework: WARN
      apache:
        catalina: WARN
        velocity: WARN

---
spring:
    profiles: local

gorg:
    username: gorg
    password: gorg
    delete:
        resources: false

management:
    metrics:
        distribution:
            sla:
                openshift_client_api_request: 10ms, 25ms, 50ms, 100ms, 500ms, 1s, 5s
                openshift_http_api_request: 10ms, 25ms, 50ms, 100ms, 500ms, 1s, 5s

logging:
    pattern:
      console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"
    # add mokey.openshift.token to ~/.spring-boot-devtools.properties


---
spring:
  profiles: openshift
